version: "3.8"

services:
  auto-register:
    build: .
    image: auto-register-csv
    container_name: auto-register-csv
    restart: always

    volumes:
      - ./users.csv:/app/users.csv
      - ./.env:/app/.env

    environment:
      CSV_PATH: /app/users.csv
      NODE_ENV: production
      MYSQL_HOST: host.docker.internal
      BASE_URL: http://host.docker.internal:3001

    extra_hosts:
      - "host.docker.internal:host-gateway"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
